# Generated by Django 5.2 on 2025-04-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_type_alter_usert_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nameuser',
            new_name='username',
        ),
    ]
