# Generated by Django 5.2 on 2025-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_nameuser_contact_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('adopt', 'adopt'), ('service', 'service')], max_length=20),
        ),
    ]
